name: test tags build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Ksu tags'     
        required: true
        default: 'main'
      kernel_branch:
          description: 'branch'     
          required: true
          default: 'ksu-patch'
          type: choice
          options:
           - ksu-patch
           - lineage-20
           - main
      kernel_repository:
          description: 'kernel_repository'     
          required: true
          default: 'kingz40o/android_kernel_xiaomi_msm8998'
          type: choice
          options:
           - kingz40o/android_kernel_xiaomi_msm8998
           - sticpaper/android_kernel_xiaomi_msm8998-ksu
      

env:
  kernel_repository: ${{github.event.inputs.kernel_repository}}
  kernel_branch: ${{github.event.inputs.kernel_branch}}
  device: sagit
  defconfig: sagit_defconfig
  use_aosp_clang: false
  clang_version: 14
  tags: ${{github.event.inputs.tags}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: install common package
        run: |
          sudo apt update
          sudo apt install -y curl zip unzip git make bc binutils-arm-linux-gnueabi binutils-aarch64-linux-gnu

      - name: checkout kernel
        uses: actions/checkout@v3
        with:
          repository: ${{ env.kernel_repository }}
          ref: ${{ env.kernel_branch }}

      - name: get latest kernel commit id
        run: |
          kernel_commit_id=$(git rev-parse HEAD)
          echo kernel_commit_id=$kernel_commit_id >> $GITHUB_ENV

      - name: "aosp-clang: get aosp clang version"
        if: ${{ env.use_aosp_clang == 'true' }}
        run: |
          aosp_clang_version=$(curl https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/build.config.constants | sed -E -n 's .*(r[0-9]{6}[a-z]?[0-9]?).* \1 p')
          echo aosp_clang_version=$aosp_clang_version >> $GITHUB_ENV

      - name: "aosp-clang: compiler restore"
        id: compiler_restore
        if: ${{ env.use_aosp_clang == 'true' }}
        uses: actions/cache/restore@v3
        with:
          path: compiler
          key: compiler-${{ env.aosp_clang_version }}

      - name: "aosp-clang: compiler download"
        id: compiler_download
        if: ${{ env.use_aosp_clang == 'true' && steps.compiler_restore.outputs.cache-hit != 'true' }}
        run: |
          curl -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-$aosp_clang_version.tar.gz
          mkdir -p compiler/aosp-clang
          tar -xf aosp-clang.tar.gz -C compiler/aosp-clang
          rm -rf aosp-clang.tar.gz

      - name: "aosp-clang: compiler save"
        id: compiler_save
        if: ${{ env.use_aosp_clang == 'true' && steps.compiler_download.outcome == 'success' }}
        uses: actions/cache/save@v3
        with:
          path: compiler
          key: ${{ steps.compiler_restore.outputs.cache-primary-key }}

      - name: "aosp-clang: setup"
        if: ${{ env.use_aosp_clang == 'true' }}
        run: |
          PATH=$(pwd)/compiler/aosp-clang/bin:$PATH
          echo PATH=$PATH >> $GITHUB_ENV

      - name: "vanilla-clang: setup"
        if: ${{ env.use_aosp_clang == 'false' }}
        run: |
          #sudo apt install -y clang-$clang_version lld-$clang_version

          #PATH=/usr/lib/llvm-$clang_version/bin:$PATH
          #echo PATH=$PATH >> $GITHUB_ENV
          sudo apt-get update -y 
          sudo apt install gcc-aarch64-linux-gnu -y
          sudo apt install gcc-arm-linux-gnueabi -y
          sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
          git clone https://github.com/kdrag0n/proton-clang --dept=1 -b master
          make clean
          make mrproper
          export PATH=$PATH:$(pwd)/proton-clang/bin/
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION=r
          export KCFLAGS=-w
          echo PATH=$PATH >> $GITHUB_ENV

      - name: setup kernelsu
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.tags }}
          #echo 'CONFIG_KPROBES=y' >> arch/arm64/configs/${{ env.defconfig }}

          cd KernelSU
          git checkout ${{ env.tags }}

      - name: export flags
        run: |
          #flags="O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-" 
          #flags="O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-"
          flags="O=out KCFLAGS=-w ARCH=arm64 CC=\"ccache clang\""
          #make O=out KCFLAGS=-w ARCH=arm64 CC="ccache clang" -j$(nproc --all)"
          echo flags=$flags >> $GITHUB_ENV

      - name: make defconfig
        run: |
          make $flags ${{ env.defconfig }}

      - name: make
        if: ${{ !inputs.pseudo_make }}
        run: |
          make $flags -j$(nproc --all)

      - name: anykernel
        run: |
          curl -Lo AnyKernel3.zip https://github.com/osm0sis/AnyKernel3/archive/refs/heads/master.zip
          unzip AnyKernel3.zip
          cd AnyKernel3-master

          cat > anykernel.sh <<EOF
          properties() { '
          do.devicecheck=1
          do.cleanup=1
          device.name1=${{ env.device }}
          '; }
          block=auto
          is_slot_device=0
          . tools/ak3-core.sh
          split_boot
          flash_boot
          EOF

          cp ../out/arch/arm64/boot/Image.gz-dtb .
          zip -r AnyKernel3-${{ env.tags }}-${{ env.device }}.zip * -x .git README.md *placeholder

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: debug-${{ env.tags }}
          body: |
            Device:${{ env.device }}            
            kernel_branch:${{github.event.inputs.kernel_branch}}
            Kernel:
            https://github.com/${{ env.kernel_repository }}/tree/${{ env.kernel_commit_id }}

            KernelSU:
            https://github.com/tiann/KernelSU/releases/tag/${{ env.tags }}
          files: |
            out/arch/arm64/boot/Image*
            AnyKernel3-master/AnyKernel3*.zip
